### ISSUE TITLE
Customized GO lists as the input data?

### ISSUE THREAD

**Issue by monjou-lai** [Guannan-Wang/GOMCL#1]
Hello, 

I am interested in testing this program for some data I have in hand.
The data I received wasn't the raw output of the GO enrichment analysis, but in table format.
Just wonder how I could prepare it as the customized GO list as specified in the paper.

Regards,
monjou

**Comment by Guannan-Wang** [comment]
Hello monjou,

Thanks for your interests in using GOMCL, and sorry for missing your comment. If you can share your GO enrichment analysis output file, I will add it into GOMCL. 
Thanks.

Guannan

**Comment by lkondratova** [comment]
I have the same question about customized input. I have standard GO .gaf format (http://geneontology.org/docs/go-annotation-file-gaf-format-2.1/) and was wondering if I can cluster terms in it with GOMCL.

**Comment by Guannan-Wang** [comment]
Hello monjou and lkondratova,

GOMCL now can take customized inputs, please have a look the example [here](https://github.com/Guannan-Wang/GOMCL#updates). Hopefully this will fit your needs.
Thanks.

Guannan
