### ISSUE TITLE
"rU" in python scripts

### ISSUE THREAD

**Issue by abulenciamiguel** [Guannan-Wang/GOMCL#10]
Hello. 
This tool is awesome.
I managed to run the py3 branch but changed a few lines in the code.

Sample error
```
open(enGOraw, "rU")
```

Kindly replace the "rU" in the python scripts into newline=''
```
open(enGOraw, newline='')
```
Hope this helps.

**Comment by Guannan-Wang** [comment]
Hello Miguel,

Glad you find it useful. Thanks for letting me know, I will fix all these relevant issues in the next release.
Thanks.

Guannan
