### ISSUE TITLE
the provided tool is currently not supported

### ISSUE THREAD

**Issue by bsnf** [Guannan-Wang/GOMCL#2]
I tested the example, but it does not work for me.
I always got the error message:

% GOMCL.py go-basic.obo Wendrich_PNAS_SD2_LR_TMO5_H_vs_L.bgo -gosize 3500 -gotype BP CC -I 1.5 -hm -nw -d -hg 0 -hgt -ssd 0

   The provided tool is currently not supported!
   [mclxIOstreamIn] no assignments yield void/empty matrix
   [mcl] new tab created
   [mcl] 0 clusters found
   ...
   ZeroDivisionError: float division by zero

Workaround:
remove  wrong test case  "else.. break" , line 122..124 in
"script/go_enrichment_result_formatter.py"

<pre>
script/go_enrichment_result_formatter.py

#  else:
#        print("The provided tool is currently not supported!") 
#        break
</pre>
Now it works fine, both GOMCL.py and GOMCL-sub.py
(testet with BiNGO)

**Comment by Guannan-Wang** [comment]
Hello bsnf,

Thanks for the interest in using GOMCL and reporting the issue. I just realized that it was a typo in script/go_enrichment_result_formatter.py, and have it fixed now. Please try with the updated code (I tested it from my end, it works fine.) and let me know if it still doesn't work for you.

Guannan
