### ISSUE TITLE
___ [mcxOptParse] unsupported option <--abc>

### ISSUE THREAD

**Issue by TessaGillett** [Guannan-Wang/GOMCL#3]
Hi,

I've been trying to test drive your tool, but I get the following error:

```
GO:0016569 is labeled as "obselete" in the obo annotation file, will be skipped!
GO:0000059 is labeled as "obselete" in the obo annotation file, will be skipped!
___ [mcxOptParse] unsupported option <--abc>
___ [mcl] error while parsing options
[mcl] do 'mcl -h' or 'man mcl'
Traceback (most recent call last):
  File "../GOMCL.py", line 77, in <module>
    go_clstr_dict, gene_clstr_dict, clstred_go_dict, clstred_gene_dict = go_assign_cluster(os.path.splitext(args.enGO)[0] + "_GOsize" + str(args.gosize) + "_" + str(args.simindex) + "_Ct" + str(args.cutoff) + "I" + str(args.inflation) + ".enGOfltrd.temp", args.simindex, args.cutoff, args.inflation)
  File "/home/tessa/Downloads/GOMCL-master/scripts/go_clustering.py", line 126, in go_assign_cluster
    go_mclgroup_dict, gene_mclgroup_dict = go_clustering(enGOfmtfltr, SI, Ct, Inf)
  File "/home/tessa/Downloads/GOMCL-master/scripts/go_clustering.py", line 100, in go_clustering
    fin_mcl = open(os.path.splitext(enGOfmtfltr)[0] + "_" + str(SI) + "_Ct" + str(Ct) + "I" + str(Inf) + ".enGOcmped.mcl.temp","rU")
IOError: [Errno 2] No such file or directory: 'Wendrich_PNAS_SD2_LR_TMO5_H_vs_L_GOsize3500_OC_Ct0.5I1.5.enGOfltrd_OC_Ct0.5I1.5.enGOcmped.mcl.temp'
```
Command line:
```
python2 ../GOMCL.py go-basic.obo Wendrich_PNAS_SD2_LR_TMO5_H_vs_L.bgo -gosize 3500 -gotype BP CC -I 1.5 -hm -nw -d -hg 0 -hgt -ssd 0
```

The same happens if I try to run it on my own files. Any ideas on what's going wrong here?

Thanks!
Tessa

**Comment by Guannan-Wang** [comment]
Hello Tessa, 

Thanks for using GOMCL and reporting this issue.
This appears to be an issue with mcl, could you let me know which version of mcl you are using (you can try "mcl --version"), and python version as well?
Thanks.

Guannan

**Comment by TessaGillett** [comment]
Hi Guannan,

Thanks for the quick response! My MCL version is mcl 1.005, 05-300. Python is 2.7.18.

**Comment by Guannan-Wang** [comment]
Hello Tessa,

I think this is a problem with MCL versions, option <--abc> doesn't seem to be supported in the version you are using (please have a look at the change log of MCL at https://micans.org/mcl/index.html?sec_software). Please upgrade your MCL to the latest version and try GOMCL again. 
Please let me know if the problem still persists.
Thanks.

Guannan

**Comment by micans** [comment]
Hi, happy to help if there is a problem. Version 05-300 is pretty ancient (16 years old). The latest stable release (14-137) is supported in quite a few Linux package managers, and should also be easy to compile from source (https://micans.org/mcl/src/mcl-14-137.tar.gz). This version certainly supports the `--abc` option.

**Comment by TessaGillett** [comment]
Hi both,

Thanks for the help! I checked and with an updated version of mcl it works fine - must have been sleeping when I installed it...
