### ISSUE TITLE
Python3

### ISSUE THREAD

**Issue by Thecatinamustang** [Guannan-Wang/GOMCL#5]
I have a beginners-question concerning the set-up:

Is this generally also running with python3?

best,

cat

**Comment by Guannan-Wang** [comment]
Hello cat,

Thanks for your interest in using GOMCL. Unfortunately, GOMCL is not compatible with python3 at this moment. But we are now in the process of making GOMCL compatible with python3, which will be released soon.
Thanks.

Guannan

**Comment by Guannan-Wang** [comment]
Hello Cat,

Sorry for the terrible delay in updating GOMCL. We have now made GOMCL compatible with python3, you can find the zipped file [GOMCL-py3.zip](https://github.com/Guannan-Wang/GOMCL/blob/master/GOMCL-py3.zip) in the main repository. It has been tested from our end using python3.8.8.
Please let us know if you run into any problems.
Thanks.

Guannan
