### ISSUE TITLE
MCL download

### ISSUE THREAD

**Issue by naomikk7** [Guannan-Wang/GOMCL#6]
Hi Guannan,
I have some issue with downloading MCL. In the website you provide, I tried their installation code:
   cd mcl-14-157
   ./configure --prefix=$HOME/local
   make install

I used version mcl-14-137 and python 3.8.8, but when I tried "mcl -h", it shows no command is found. Can you let me know what version of MCL you download and how you successfully download it? Without this MCL, I cannot run GOMCL successfully. 

Here is the error I got:

Making install in .
make[2]: Nothing to be done for `install-exec-am'.
make[2]: Nothing to be done for `install-data-am'.
Making install in util
make[2]: Nothing to be done for `install-exec-am'.
make[2]: Nothing to be done for `install-data-am'.
Making install in img
make[2]: Nothing to be done for `install-exec-am'.
test -z "/Users/naomini/local/share/doc/mcl/examples" || ../autofoo/install-sh -c -d "/Users/naomini/local/share/doc/mcl/examples"
 /usr/bin/install -c -m 644 fa_1024.png fa_400.png fa_600.png fa_large.png fa.ps falkner-bidi.ps falkner.ps small.ps small.png '/Users/naomini/local/share/doc/mcl/examples'
Making install in graphs
make[2]: Nothing to be done for `install-exec-am'.
test -z "/Users/naomini/local/share/doc/mcl/examples" || ../autofoo/install-sh -c -d "/Users/naomini/local/share/doc/mcl/examples"
 /usr/bin/install -c -m 644 falkner.mci falkner2.mci falkner.coords make-falkner.pl proteins.mci matula.mci lattice.mci honey.mci seven.mci infinity.mci friends small.mci small.map small.tab fznyy.tab fznyy.mci small64.mci petersen.mci tiny-min.mci tiny-nil.mci tiny-nilnine.mci tiny-ninenil.mci tiny-one.mci tiny-zero.mci data.raw data.hdr data.tab data.abc.raw data.abc.hdr data.abc.map T Tx Ty Txy '/Users/naomini/local/share/doc/mcl/examples'
Making install in doc
make[2]: Nothing to be done for `install-exec-am'.
test -z "/Users/naomini/local/share/doc/mcl" || ../autofoo/install-sh -c -d "/Users/naomini/local/share/doc/mcl"
 /usr/bin/install -c -m 644 mcl.html mcl.ps mcl.txt mclcm.html mclcm.ps mclcm.txt mclfaq.html mclfaq.ps mclfaq.txt mclfamily.html mclfamily.ps mcx.html mcx.ps mcxi.html mcxi.ps clm.html clm.ps mcxconvert.html mcxconvert.ps mcxarray.html mcxarray.ps mcxdump.html mcxdump.ps mcxdiameter.html mcxdiameter.ps mcxerdos.html mcxerdos.ps mcxalter.html mcxalter.ps mcxclcf.html mcxclcf.ps mcxctty.html mcxctty.ps mcxrand.html mcxrand.ps mcxload.html mcxload.ps mcxsubs.html mcxsubs.ps mcxmap.html '/Users/naomini/local/share/doc/mcl'
 /usr/bin/install -c -m 644 mcxmap.ps mcxquery.html mcxquery.ps mcxassemble.html mcxassemble.ps mclpipeline.html mclpipeline.ps index.html mclindex.ps clmimac.html clmimac.ps clmoptics.html clmoptics.ps clmclose.html clmclose.ps clmresidue.html clmresidue.ps clmdist.html clmdist.ps clmvol.html clmvol.ps clminfo.html clminfo.ps clminfo2.html clminfo2.ps clmmate.html clmmate.ps clmmeet.html clmmeet.ps clmformat.html clmformat.ps clmorder.html clmorder.ps minimcl mcxio.html mcxio.ps clmprotocols.html clmprotocols.ps clmprotocols2.html clmprotocols2.ps '/Users/naomini/local/share/doc/mcl'
 /usr/bin/install -c -m 644 tingea.log.html tingea.log.ps mclmcl.txt '/Users/naomini/local/share/doc/mcl'
test -z "/Users/naomini/local/share/man/man1" || ../autofoo/install-sh -c -d "/Users/naomini/local/share/man/man1"
 /usr/bin/install -c -m 644 mcl.1 mclcm.1 clm.1 mcx.1 mcxi.1 clmresidue.1 clmclose.1 clmoptics.1 clmimac.1 clmmate.1 clmmeet.1 clmformat.1 clmvol.1 clmdist.1 clminfo2.1 clminfo.1 clmorder.1 mcxconvert.1 mcxassemble.1 mcxmap.1 mcxsubs.1 mcxload.1 mcxdump.1 mcxarray.1 mcxrand.1 mcxalter.1 mcxerdos.1 mcxdiameter.1 mcxctty.1 mcxclcf.1 mcxquery.1 mclpipeline.1 '/Users/naomini/local/share/man/man1'
test -z "/Users/naomini/local/share/man/man5" || ../autofoo/install-sh -c -d "/Users/naomini/local/share/man/man5"
 /usr/bin/install -c -m 644 mcxio.5 clmprotocols2.5 clmprotocols.5 '/Users/naomini/local/share/man/man5'
test -z "/Users/naomini/local/share/man/man7" || ../autofoo/install-sh -c -d "/Users/naomini/local/share/man/man7"
 /usr/bin/install -c -m 644 mclindex.7 mclfamily.7 mclfaq.7 tingea.log.7 '/Users/naomini/local/share/man/man7'
Making install in src
Making install in .
make[3]: Nothing to be done for `install-exec-am'.
make[3]: Nothing to be done for `install-data-am'.
Making install in clew
make[3]: Nothing to be done for `install-exec-am'.
make[3]: Nothing to be done for `install-data-am'.
Making install in mcl
make[3]: Nothing to be done for `install-exec-am'.
make[3]: Nothing to be done for `install-data-am'.
Making install in gryphon
make[3]: Nothing to be done for `install-exec-am'.
make[3]: Nothing to be done for `install-data-am'.
Making install in impala
make[3]: Nothing to be done for `install-exec-am'.
make[3]: Nothing to be done for `install-data-am'.
Making install in shcl
test -z "/Users/naomini/local/bin" || ../../autofoo/install-sh -c -d "/Users/naomini/local/bin"
  /usr/bin/install -c clmformat clm '/Users/naomini/local/bin'
test -z "/Users/naomini/local/bin" || ../../autofoo/install-sh -c -d "/Users/naomini/local/bin"
 /usr/bin/install -c mclpipeline '/Users/naomini/local/bin'
make[3]: Nothing to be done for `install-data-am'.
Making install in shmcl
test -z "/Users/naomini/local/bin" || ../../autofoo/install-sh -c -d "/Users/naomini/local/bin"
  /usr/bin/install -c mcl mclcm '/Users/naomini/local/bin'
make[3]: Nothing to be done for `install-data-am'.
Making install in shmx
test -z "/Users/naomini/local/bin" || ../../autofoo/install-sh -c -d "/Users/naomini/local/bin"
  /usr/bin/install -c mcx mcxsubs mcxmap mcxassemble mcxarray mcxdump mcxload mcxrand '/Users/naomini/local/bin'
make[3]: Nothing to be done for `install-data-am'.
Making install in shmcx
test -z "/Users/naomini/local/bin" || ../../autofoo/install-sh -c -d "/Users/naomini/local/bin"
  /usr/bin/install -c mcxi '/Users/naomini/local/bin'
make[3]: Nothing to be done for `install-data-am'.
Making install in shmcxquery
make[3]: Nothing to be done for `install-exec-am'.
make[3]: Nothing to be done for `install-data-am'.
Making install in alien
make[4]: Nothing to be done for `install-exec-am'.
make[4]: Nothing to be done for `install-data-am'.
Making install in include
Making install in .
make[3]: Nothing to be done for `install-exec-am'.
make[3]: Nothing to be done for `install-data-am'.
Making install in scripts
test -z "/Users/naomini/local/bin" || ../autofoo/install-sh -c -d "/Users/naomini/local/bin"
 /usr/bin/install -c clxdo '/Users/naomini/local/bin'
make[2]: Nothing to be done for `install-data-am'.
Making install in testing
Making install in .
make[3]: Nothing to be done for `install-exec-am'.
make[3]: Nothing to be done for `install-data-am'.
Making install in stream
make[3]: Nothing to be done for `install-exec-am'.
make[3]: Nothing to be done for `install-data-am'.
Making install in blast
make[3]: Nothing to be done for `install-exec-am'.
make[3]: Nothing to be done for `install-data-am'.
Making install in setops
make[3]: Nothing to be done for `install-exec-am'.
make[3]: Nothing to be done for `install-data-am'.

Thanks,
Naomi

**Comment by Guannan-Wang** [comment]
Hello Naomi,

Thanks for reaching out. Please try to install MCL through anaconda: https://anaconda.org/bioconda/mcl, which will give you the full access to MCL. 
Thanks.

Guannan

**Comment by HaoGroup** [comment]
Hi Guannan,
Thanks for your help! This makes it much easier.
I have another question about your test codes. I found you use "-gotype BP" in your code. What does BP mean? Are there any other types? 
Plus, can you pls explain "CC" and "-C 1" in your test codes? I am trying to use different -Ct and -I values to select the best combination for my data. I noticed that you didn't put -Ct in your test run. Does it just assume -Ct = 0.5? 
Thank you very much! 

Best,
Naomi

**Comment by naomikk7** [comment]
Hi Guannan,
Thanks for your help! This makes it much easier.
I have another question about your test codes. I found you use "-gotype BP" in your code. What does BP mean? Are there any other types?
Plus, can you pls explain "CC" and "-C 1" in your test codes? I am trying to use different -Ct and -I values to select the best combination for my data. I noticed that you didn't put -Ct in your test run. Does it just assume -Ct = 0.5?
Thank you very much!

Best,
Naomi

**Comment by Guannan-Wang** [comment]
Hello Naomi,

"-gotype" refers to the types of GO terms of interest. It can be one or more of the three biological domains defined by [Gene Ontology Consortium](http://geneontology.org/docs/ontology-documentation/):  Molecular Function (MF), Cellular Component (CC), and Biological Process (BP).
"-C 1" is only applicable for GOMCL-sub.py, it simply represents the cluster (derived from GOMCL.py) that you would like to do a sub-clustering with. Yes, the default Ct is 0.5, which you can change according to your need. You can check these options with "GOMCL-sub.py --help". 
Thanks.

Guannan

**Comment by naomikk7** [comment]
Thank you so much!
